### ISSUE TITLE
dvlopt.kstreams.stream/process-values throws  java.lang.ClassCastException

### ISSUE THREAD

**Issue by smessems** [dvlopt/kafka.clj#6]
I am getting the following exception when using process-values:

```
 Unhandled java.lang.ClassCastException
   dvlopt.kafka._interop.java$transformer$reify__886 cannot be cast to
   org.apache.kafka.streams.kstream.ValueTransformerWithKey

                  java.clj: 1772  dvlopt.kafka.-interop.java/value-transformer-with-key-supplier/reify
KStreamTransformValues.java:   36  org.apache.kafka.streams.kstream.internals.KStreamTransformValues/get
InternalTopologyBuilder.java:  238  org.apache.kafka.streams.processor.internals.InternalTopologyBuilder$ProcessorNodeFactory/build
InternalTopologyBuilder.java:  875  org.apache.kafka.streams.processor.internals.InternalTopologyBuilder/build
InternalTopologyBuilder.java:  836  org.apache.kafka.streams.processor.internals.InternalTopologyBuilder/build
InternalTopologyBuilder.java:  819  org.apache.kafka.streams.processor.internals.InternalTopologyBuilder/build
         KafkaStreams.java:  673  org.apache.kafka.streams.KafkaStreams/<init>
         KafkaStreams.java:  628  org.apache.kafka.streams.KafkaStreams/<init>
         KafkaStreams.java:  538  org.apache.kafka.streams.KafkaStreams/<init>
              kstreams.clj:   88  dvlopt.kstreams/app
              kstreams.clj:   36  dvlopt.kstreams/app
```

It seems that ValueTransformerWithKeySupplier::get should return ValueTransformerWithKey.
So perhaps, **value-transformer-with-key-supplier** should call **value-transformer-with-key** instead of **transformer**?

**Comment by dvlopt** [comment]
Thanks ! Indeed, simple mistake. Fixed in version 1.0.0-beta2

**Comment by smessems** [comment]
Hi, there is an error in the params order inside process-values:
   (process-values stream
                   processor
                   nil))
  (^KStream
   [^KStream stream **options processor**]

It seems that the processor should be the second param and the option as third param.
(Not sure if you get notification on comments on closed issues - I will open a new issue in few days)

**Comment by dvlopt** [comment]
Right ! That is why I keep it in beta for the time being. It is already being used in production but there are probably a few tiny bugs like that. 

Fixed in the latest commit. Do you see anything else before I release it on clojars ?

**Comment by smessems** [comment]
Looks good so far. I was able to convert my system to the new version.
I did not verified performance impact though. But  I do not forsee issues.

**Comment by dvlopt** [comment]
You were using Milena ? The previous iteration ? From now on, the API is considered stable unless something significantly changes in the underlying Java libs.

When it comes to performance, as always, there is some cost to "clojurifying" Java libraries. However, I expected some of the heavy load is JITted away.

**Comment by smessems** [comment]
Yes, I was using milena.
Awesome!
