### ISSUE TITLE
join-windows  function args error

### ISSUE THREAD

**Issue by pilot11** [dvlopt/kafka.clj#7]
In ns `dvlopt.kstreams.stream` ,there are functions `join-with-stream` `left-join-with-stream` `outer-join-with-stream` invoke function `join-windows` as  `(K.-interop.java/join-windows interval)`,ues one arg. Do not match the args of function `join-windows` defined in ns `dvlopt.kafka.-interop.java` with two args as `[interval options]`.

**Comment by dvlopt** [comment]
Thanks, fixed in latest release.
